name: 'Atlantis terraform drift detection'
description: 'Some automation to detect drift inside atlantis via the remote /plan endpoint'
branding:
  icon: 'activity'
  color: 'blue'
runs:
  using: 'docker'
  image: 'Dockerfile'