name: 'Atlantis terraform drift detection'
description: 'Some automation to detect drift inside atlantis via the remote /plan endpoint'
branding:
  icon: 'activity'
  color: 'blue'
runs:
  using: 'docker'
  # TODO: Figure out a way to auto update this. It's very useful for speeding up the action to not have it build the
  # container each run
  image: 'docker://ghcr.io/cresta/atlantis-drift-detection:v1'