name: Build and test code

on:
  push:
    tags:
      - v*
    branches:
      - master
      - main
  pull_request:


jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          args: "--timeout 5m"
      - name: Build
        run: go build -mod=readonly ./cmd/atlantis-drift-detection/main.go
      - name: Verify
        run: go mod verify
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Test
        run: go test -v ./...
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        id: buildx
        with:
          install: true
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=ref,event=pr
            type=semver,pattern=v{{major}},enable=${{ github.event_name == 'push' && contains(github.ref, 'refs/tags/') }}
          images: |
            ghcr.io/cresta/atlantis-drift-detection
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          # Push only if tag
          push: ${{ github.event_name == 'push' && contains(github.ref, 'refs/tags/') }}
          platforms: linux/amd64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}